// Generated by sqltyper from createUser.sql.
// Do not edit directly. Instead, edit createUser.sql and re-run sqltyper.


import { ClientBase, Pool } from 'pg'

export async function createUser(
  client: ClientBase | Pool, params: { identifier: string, status: number, encrypted_blob: string, server_password: string }
): Promise<number> {
    const result = await client.query(`\
insert into users (identifier, status, encrypted_blob, server_password) values ($1, $2, $3, $4);`, [ params.identifier, params.status, params.encrypted_blob, params.server_password ])
    return result.rowCount
}
