// Generated by sqltyper from fetchParticipant.sql.
// Do not edit directly. Instead, edit fetchParticipant.sql and re-run sqltyper.


import { ClientBase, Pool } from 'pg'

export async function fetchParticipant(
  client: ClientBase | Pool, params: { uuid: string }
): Promise<Array<{ 'commitment': string; 'name': string; 'email': string; 'role': string; 'residence': string }>> {
    const result = await client.query(`\
select 
    commitment,
    name,
    email,
    role,
    residence
from commitments c
join pretix_participants p on c.participant_email=p.email
where c.uuid = $1;`, [ params.uuid ])
    return result.rows
}
