// Generated by sqltyper from fetchUser.sql.
// Do not edit directly. Instead, edit fetchUser.sql and re-run sqltyper.


import { ClientBase, Pool } from 'pg'

export async function fetchUser(
  client: ClientBase | Pool, params: { searched_identifier: string }
): Promise<Array<{ 'identifier': string; 'status': number; 'created_at': Date; 'salt': string; 'encrypted_blob': string; 'updated_at': Date }>> {
    const result = await client.query(`\
select identifier, status, created_at, salt, encrypted_blob, updated_at from users where identifier = $1;`, [ params.searched_identifier ])
    return result.rows
}
