// Generated by sqltyper from fetchParticipantEmails.sql.
// Do not edit directly. Instead, edit fetchParticipantEmails.sql and re-run sqltyper.


import { ClientBase, Pool } from 'pg'

export async function fetchParticipantEmails(
  client: ClientBase | Pool
): Promise<Array<{ 'email': string }>> {
    const result = await client.query(`\
select email from pretix_participants;`)
    return result.rows
}
