// auto-generated by circomkit
pragma circom 2.1.8;

include "../proto-pod-gpc.circom";

component main {public[entryObjectIndex, entryNameHash, entryIsValueHashRevealed, virtualEntryIsValueHashRevealed, entryEqualToOtherEntryByIndex, ownerEntryIndex, ownerExternalNullifier, ownerIsNullfierHashRevealed, numericValueEntryIndices, numericMinValues, numericMaxValues, tupleIndices, listComparisonValueIndex, listContainsComparisonValue, listValidValues, globalWatermark]} = ProtoPODGPC(3, 10, 8, 4, 2, 20, 1, 4);
