// auto-generated by circomkit
pragma circom 2.1.8;

include "../proto-pod-gpc.circom";

component main {public[entryObjectIndex, entryNameHash, entryIsValueEnabled, entryIsValueHashRevealed, virtualEntryIsValueHashRevealed, entryEqualToOtherEntryByIndex, ownerEntryIndex, ownerExternalNullifier, ownerIsNullfierHashRevealed, tupleIndices, listComparisonValueIndex, listContainsComparisonValue, listValidValues, globalWatermark]} = ProtoPODGPC(1, 5, 6, 0, 0, 0, 0);
