// auto-generated by circomkit
pragma circom 2.1.8;

include "../proto-pod-gpc.circom";

component main {public[objectSignerPubkeyAx, objectSignerPubkeyAy, entryObjectIndex, entryNameHash, entryIsValueEnabled, entryIsValueHashRevealed, entryEqualToOtherEntryByIndex, ownerEntryIndex, ownerExternalNullifier, ownerIsNullfierHashRevealed, tupleIndices, memberIndex, membershipList, globalWatermark]} = ProtoPODGPC(3, 10, 8, 2, 20, 1, 4);
