// auto-generated by circomkit
pragma circom 2.1.8;

include "../proto-pod-gpc.circom";

component main {public[entryObjectIndex, entryNameHash, entryIsValueHashRevealed, virtualEntryIsValueHashRevealed, entryEqualToOtherEntryByIndex, ownerEntryIndex, ownerExternalNullifier, ownerIsNullfierHashRevealed, numericValueEntryIndices, numericMinValues, numericMaxValues, tupleIndices, listComparisonValueIndex, listContainsComparisonValue, listValidValues, globalWatermark]} = ProtoPODGPC(1, 5, 6, 2, 0, 0, 0, 0);
